name: Laravel Pint

on:
  push:
    branches: [ master ]

jobs:
  laravel-pint:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: composer install --prefer-dist
      - name: Run pint
        run: ./vendor/bin/pint --test
